version: '3'

dotenv: ['.env']

tasks:
  default:
    cmds:
      - task: apply-infra
      - task: apply-platform
      - echo "Deployment successful"

  apply-infra:
    dir: ./infra
    cmds:
      - terraform apply -auto-approve

  apply-platform:
    dir: ./platform
    vars:
      MINIO_ADDRESS:
        sh: terraform -chdir=../infra output -raw minio_address
      VAULT_ADDRESS:
        sh: terraform -chdir=../infra output -raw vault_address
    env:
      TF_VAR_minio_address: "{{.MINIO_ADDRESS}}"
      TF_VAR_vault_address: "{{.VAULT_ADDRESS}}"
    cmds:
      - terraform apply -auto-approve
