version: '3'

dotenv: ['.env']

tasks:
  default:
    cmds:
      - task: apply-infra
      - task: apply-platform
      - echo "Deployment successful"

  apply-infra:
    dir: ./infra
    cmds:
      - terraform apply -auto-approve

  apply-platform:
    deps: [apply-infra]
    dir: ./platform
    vars:
      INFRA_OUTPUTS:
        sh: terraform -chdir=../infra output -json
    cmds:
      - vault status
      - export TF_VAR_kubernetes_ip={{.INFRA_OUTPUTS | jq -r .kubernetes_ip.value}}
      - export TF_VAR_vault_ip={{.INFRA_OUTPUTS | jq -r .vault_ip.value}}
      - terraform apply -auto-approve
