apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: zot
  namespace: zot
spec:
  interval: 2h0m
  url: http://zotregistry.dev/helm-charts
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: zot
  namespace: zot
spec:
  interval: 30m
  chart:
    spec:
      version: "0.1.122"
      chart: zot
      sourceRef:
        kind: HelmRepository
        name: zot
        namespace: zot
      interval: 1h

  values:
    service:
      type: ClusterIP
      port: 5000

    ingress:
      enabled: true
      className: traefik
      hosts:
        - host: registry.${DOMAIN}
          paths:
            - path: /

    persistence: true
    pvc:
      create: true
      accessModes:
        - ReadWriteOnce
      # TODO: If we ever go multi-node, the default local-path storage class won't work
      storage: 50Gi

    mountConfig: true
    configFiles:
      config.json: |
        {
          "storage": {
            "rootDirectory": "/var/lib/registry"
          },
          "http": {
            "address": "0.0.0.0",
            "port": "5000",
            "auth": {
              "htpasswd": {
                "path": "/secrets/zot/htpasswd"
              }
            }
          },
          "log": {
            "level": "warn"
          }
        }

    externalSecrets:
      - secretName: zot-credentials
        mountPath: /secrets/zot
