apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: monitoring
resources:
  - alertmanager-secret.yml
  - grafana.yml
  - k8s-monitoring.yml
  - loki.yml
  - mimir.yml
  - repository.yml
  - tempo.yml
  - podmonitor.yml
  - alerts
configMapGenerator:
  - name: flux-kube-state-metrics-config
    files:
      - kube-state-metrics-config.yml
    options:
      labels:
        app.kubernetes.io/part-of: flux
        app.kubernetes.io/component: monitoring
  - name: grafana-dashboards
    files:
      - dashboards/control-plane.json
      - dashboards/cluster.json
      - dashboards/game-server.json
    options:
      labels:
        grafana_dashboard: "1"
        app.kubernetes.io/part-of: flux
        app.kubernetes.io/component: monitoring
configurations:
  - kustomizeconfig.yml
