apiVersion: image.toolkit.fluxcd.io/v1
kind: ImageRepository
metadata:
  name: db-migration
  namespace: flux-system
spec:
  image: registry.${DOMAIN}/game/game-db-migration
  interval: 5m0s
  secretRef:
    name: zot-registry-credentials
---
apiVersion: image.toolkit.fluxcd.io/v1
kind: ImageRepository
metadata:
  name: game-provisioner
  namespace: flux-system
spec:
  image: registry.${DOMAIN}/game/game-provisioner
  interval: 5m0s
  secretRef:
    name: zot-registry-credentials
---
apiVersion: image.toolkit.fluxcd.io/v1
kind: ImageRepository
metadata:
  name: game-server
  namespace: flux-system
spec:
  image: registry.${DOMAIN}/game/game-server
  interval: 5m0s
  secretRef:
    name: zot-registry-credentials
---
apiVersion: image.toolkit.fluxcd.io/v1
kind: ImageRepository
metadata:
  name: web-server
  namespace: flux-system
spec:
  image: registry.${DOMAIN}/game/web-server
  interval: 5m0s
  secretRef:
    name: zot-registry-credentials
