apiVersion: image.toolkit.fluxcd.io/v1
kind: ImageRepository
metadata:
  name: db-migration
  namespace: flux-system
spec:
  image: rejdeboer/game-db-migration
  interval: 5m0s
---
apiVersion: image.toolkit.fluxcd.io/v1
kind: ImageRepository
metadata:
  name: game-provisioner 
  namespace: flux-system
spec:
  image: rejdeboer/game-provisioner
  interval: 5m0s
---
apiVersion: image.toolkit.fluxcd.io/v1
kind: ImageRepository
metadata:
  name: game-server
  namespace: flux-system
spec:
  image: rejdeboer/game-server
  interval: 5m0s
---
apiVersion: image.toolkit.fluxcd.io/v1
kind: ImageRepository
metadata:
  name: web-server
  namespace: flux-system
spec:
  image: rejdeboer/web-server
  interval: 5m0s

