apiVersion: image.toolkit.fluxcd.io/v1
kind: ImageRepository
metadata:
  name: db-migration
  namespace: flux-system
spec:
  image: rejdeboer/mmo-db-migration
  interval: 5m0s
---
apiVersion: image.toolkit.fluxcd.io/v1
kind: ImageRepository
metadata:
  name: mmo-provisioner 
  namespace: flux-system
spec:
  image: rejdeboer/mmo-provisioner
  interval: 5m0s
---
apiVersion: image.toolkit.fluxcd.io/v1
kind: ImageRepository
metadata:
  name: mmo-server
  namespace: flux-system
spec:
  image: rejdeboer/mmo-server
  interval: 5m0s
---
apiVersion: image.toolkit.fluxcd.io/v1
kind: ImageRepository
metadata:
  name: web-server
  namespace: flux-system
spec:
  image: rejdeboer/web-server
  interval: 5m0s

