apiVersion: batch/v1
kind: Job
metadata:
  name: db-migration
  namespace: default
spec:
  template:
    spec:
      restartPolicy: Never
      containers:
      - name: migration
        image: rejdeboer/mmo-db-migration:latest
        env:
          - name: DB_HOST
            value: postgres-main-rw
          - name: DB_PORT
            value: "5432"
          - name: DB_NAME
            value: mmo
          - name: DB_USERNAME
            valueFrom:
              secretKeyRef:
                name: pg-secret
                key: username
          - name: DB_PASSWORD
            valueFrom:
              secretKeyRef:
                name: pg-secret
                key: password
        command: ["/bin/sh", "-c"]
        args:
          - |
            sqlx migrate run --database-url="postgresql://${DB_USER}:${DB_PASSWORD}@${DB_HOST}/${DB_NAME}?sslmode=disable"
