# TODO: I'm not sure if agones is the right tool for this game
# Might need to refactor to using statefulsets later
apiVersion: agones.dev/v1
kind: Fleet
metadata:
  name: game-server
  namespace: default
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: "25%"
      maxUnavailable: "25%"
  template:
    metadata:
      labels:
        # TODO: Do we need this?
        realm: main
    spec:
      container: game-server
      ports:
      - name: default
        protocol: UDP
        containerPort: 7777
      template:
        metadata:
          labels:
            app: game-server
        spec:
          containers:
          - name: game-server
            image: rejdeboer/game-server:main-74bc879-1763324843 
            resources:
              requests:
                memory: "1Gi"
                cpu: "1000m"
              limits:
                memory: "1Gi"
                cpu: "1000m"
            ports:
            - containerPort: 7777
              protocol: UDP
            volumeMounts:
            # - name: assets-volume
            #   mountPath: /app/assets
            envFrom:
            - configMapRef:
                name: game-server-config
            env:
            - name: APP_SERVER__NETCODE_PRIVATE_KEY
              valueFrom:
                secretKeyRef:
                  name: netcode-secret
                  key: private-key
            - name: APP_DATABASE__PORT
              value: "5432"
            - name: APP_DATABASE__NAME
              value: "mmo"
            - name: APP_DATABASE__HOST
              value: "postgres-main-rw"
            - name: APP_DATABASE__USERNAME
              valueFrom:
                secretKeyRef:
                  name: pg-secret
                  key: username
            - name: APP_DATABASE__PASSWORD
              valueFrom:
                secretKeyRef:
                  name: pg-secret
                  key: password
            - name: APP_TRACING__FORMAT
              value: json
            - name: APP_TRACING__OTEL_EXPORTER_ENDPOINT
              value: http://alloy.monitoring.svc.cluster.local:4317
          volumes:
          # - name: assets-volume
          #   configMap:
          #     name: assets-config
---
apiVersion: v1
kind: Service
metadata:
  name: game-server-metrics
  namespace: default
  labels:
    app: game-server-metrics
spec:
  selector:
    app: game-server
  ports:
    - name: default
      protocol: TCP
      port: 9000
      targetPort: 9000
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: game-server-metrics
  namespace: monitoring
spec:
  selector:
    matchLabels:
      app: game-server-metrics
  namespaceSelector:
    matchNames:
    - default
  endpoints:
  - port: default
    path: /
    interval: 15s
