apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: loki
  namespace: monitoring
spec:
  interval: 5m
  dependsOn:
    - name: kube-prometheus-stack
  chart:
    spec:
      version: "6.48"
      chart: loki
      sourceRef:
        kind: HelmRepository
        name: grafana-charts
      interval: 60m
  values:
    deploymentMode: SingleBinary
    global:
      extraEnv:
      - name: LOKI_S3_ACCESS_KEY
        valueFrom:
          secretKeyRef:
            name: loki-s3
            key: access-key
      - name: LOKI_S3_SECRET_KEY
        valueFrom:
          secretKeyRef:
            name: loki-s3
            key: secret-key
      - name: LOKI_S3_BUCKET
        valueFrom:
          secretKeyRef:
            name: loki-s3
            key: bucket
      - name: LOKI_S3_ENDPOINT
        valueFrom:
          secretKeyRef:
            name: loki-s3
            key: endpoint
    loki:
      commonConfig:
        replication_factor: 1
      storage:
        type: 's3'
        bucketNames:
          chunks: ${LOKI_S3_BUCKET}
          ruler: ${LOKI_S3_BUCKET}
          admin: ${LOKI_S3_BUCKET}
        endpoint: ${LOKI_S3_ENDPOINT}
        insecure: true
        s3ForcePathStyle: true
        accessKeyId: ${LOKI_S3_ACCESS_KEY}
        secretAccessKey: ${LOKI_S3_SECRET_KEY}
      schemaConfig:
        configs:
          - from: "2024-01-01"
            store: tsdb
            object_store: filesystem
            schema: v13
            index:
              prefix: index_
              period: 24h
      storage_config:
        filesystem:
          directory: /var/loki/chunks

    singleBinary:
      replicas: 0
      persistence:
        enabled: true
        size: 10Gi

    monitoring:
      selfMonitoring:
        enabled: false
        grafanaAgent:
          installOperator: false
      lokiCanary:
        enabled: false

    gateway:
      enabled: true
