apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../../operator/config/default
images:
  - name: controller
    newName: ghcr.io/rejdeboer/realm-operator # {"$imagepolicy": "flux-system:realm-operator:name"}
    newTag: main-554cc99-1786452354 # {"$imagepolicy": "flux-system:realm-operator:tag"}
