apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: web-server
  namespace: default
spec:
  # entryPoints:
  #   - websecure # Assumes you are using the 'websecure' entrypoint for HTTPS
  routes:
  - match: Host(`mmo.homelab.io`)
    kind: Rule
    services:
    - name: web-server 
      port: 80
  # tls:
  #   certResolver: letsencrypt 
  #   domains:
  #   - main: "mmo.homelab.io"
---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: grafana-dashboard
  namespace: monitoring
spec:
  # entryPoints:
  #   - websecure # Assumes you are using the 'websecure' entrypoint for HTTPS
  routes:
  - match: Host(`grafana.homelab.io`)
    kind: Rule
    services:
    - name: kube-prometheus-stack-grafana 
      port: 80
  # tls:
  #   certResolver: letsencrypt 
  #   domains:
  #   - main: "grafana.homelab.io"
