apiVersion: v1
kind: Service
metadata:
  name: web-server
  namespace: default
spec:
  ports:
    - port: 80
      targetPort: 8000
      protocol: TCP
  selector:
    app: web-server
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-server
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: web-server
  template:
    metadata:
      labels:
        app: web-server
    spec:
      containers:
        - name: web-server
          image: rejdeboer/web-server:latest
          resources:
            requests:
              memory: "256Mi"
              cpu: "300m"
            limits:
              memory: "512Mi"
              cpu: "500m"
          ports:
            - containerPort: 8000
          env:
            - name: ENVIRONMENT
              value: production
            - name: APP_APPLICATION__HOST
              value: "127.0.0.1"
            - name: APP_APPLICATION__PORT
              value: "8000"
            - name: APP_DATABASE__PORT
              value: "5432"
            - name: APP_DATABASE__DB_NAME
              value: "mmo"
            - name: APP_DATABASE__HOST
              value: "postgres-main-rw"
            - name: APP_DATABASE__USERNAME
              valueFrom:
                secretKeyRef:
                  name: pg-secret
                  key: username
            - name: APP_DATABASE__PASSWORD
              valueFrom:
                secretKeyRef:
                  name: pg-secret
                  key: password
