apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: deploy
  namespace: flux-system
spec:
  dependsOn:
    - name: pre-deploy
  interval: 10m0s
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./deploy
  prune: true
  wait: true
  timeout: 5m0s
  patches:
    - patch: |
        - op: replace
          path: /data/ENVIRONMENT
          value: staging
      target:
        kind: ConfigMap
        name: game-server-config
