apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../base
  - cluster-vars.yml
  - flux-system
patches:
  - target:
      kind: Kustomization
      name: platform-cert-manager-config
    patch: |
      - op: add
        path: /spec/patches
        value:
          - patch: |
              - op: replace
                path: /spec/acme/server
                value: https://acme-v02.api.letsencrypt.org/directory
            target:
              kind: ClusterIssuer
              name: letsencrypt
  - target:
      kind: Kustomization
      name: apps
    patch: |
      - op: replace
        path: /spec/path
        value: ./kubernetes/apps/staging
