apiVersion: v1
kind: Namespace
metadata:
  name: agones-system
  labels:
    toolkit.fluxcd.io/tenant: sre-team
---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: agones
  namespace: flux-system
spec:
  interval: 24h
  url: https://agones.dev/chart/stable
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: agones
  namespace: flux-system
spec:
  interval: 30m
  chart:
    spec:
      chart: agones
      version: "1.50.0"
      sourceRef:
        kind: HelmRepository
        name: agones
        namespace: flux-system
      interval: 12h
  targetNamespace: agones-system
  values:
    agones:
      metrics:
        serviceMonitor:
          enabled: true
