apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - agones.yml
  # - cert-manager.yml
  - cnpg.yml
  # - ingress-nginx.yml
  - kube-prometheus-stack
  - loki-stack
  # TODO: Once we gain more resource, we can use longhorn for HA
  # - longhorn.yml
  - metallb.yml
  - sealed-secrets.yml
