apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: metallb
  namespace: flux-system 
spec:
  interval: 30m
  url: https://metallb.github.io/metallb
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: metallb
  namespace: flux-system 
spec:
  interval: 15m
  chart:
    spec:
      chart: metallb
      version: "0.15.2" 
      sourceRef:
        kind: HelmRepository
        name: metallb
        namespace: flux-system 
      interval: 5m
  install:
    createNamespace: true
    remediation: { retries: 3 }
  upgrade:
    remediation:
      remediateLastFailure: true
    cleanupOnFail: true
  releaseName: metallb
