apiVersion: v1
kind: Namespace
metadata:
  name: rustfs
---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: rustfs
  namespace: flux-system
spec:
  interval: 24h
  url: https://charts.rustfs.com
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: rustfs
  namespace: flux-system
spec:
  interval: 30m
  chart:
    spec:
      chart: rustfs
      version: "*"
      sourceRef:
        kind: HelmRepository
        name: rustfs
        namespace: flux-system
      interval: 12h
  targetNamespace: rustfs
  values:
    mode: 
      standalone:
        enabled: "true"
