apiVersion: v1
kind: Namespace
metadata:
  name: sealed-secrets
  labels:
    toolkit.fluxcd.io/tenant: sre-team
---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: sealed-secrets
  namespace: flux-system
spec:
  interval: 1h
  url: https://bitnami-labs.github.io/sealed-secrets
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: sealed-secrets
  namespace: flux-system 
spec:
  interval: 15m
  chart:
    spec:
      chart: sealed-secrets
      version: "2.17.3" 
      sourceRef:
        kind: HelmRepository
        name: sealed-secrets 
        namespace: flux-system
  install:
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
  targetNamespace: sealed-secrets
