apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: tempo
  namespace: monitoring
spec:
  interval: 5m
  dependsOn:
    - name: kube-prometheus-stack
  chart:
    spec:
      version: "1.24"
      chart: tempo
      sourceRef:
        kind: HelmRepository
        name: grafana-charts
      interval: 60m
  values:
    # storage:
    #   trace:
    #     backend: s3
    #     s3:
    #       endpoint: "http://<YOUR_MINIO_VM_IP>:9000"
    #       bucket: "tempo-data"
    #       access_key: ""
    #       secret_key: ""
    #       insecure: true
    #       s3ForcePathStyle: true
    tempo:
      receivers:
        otlp:
          protocols:
            grpc:
              endpoint: 0.0.0.0:4317
            http:
              endpoint: 0.0.0.0:4318
    storage:
      trace:
        backend: local
        local:
          path: /var/tempo/traces
        wal:
          path: /var/tempo/wal

    persistence:
      enabled: true
      size: 10Gi
    #   extraEnv:
      # - name: S3_ACCESS_KEY_ID
      #   valueFrom:
      #     secretKeyRef:
      #       name: minio-credentials
      #       key: access_key
      # - name: S3_SECRET_ACCESS_KEY
      #   valueFrom:
      #     secretKeyRef:
      #       name: minio-credentials
      #       key: secret_key
      #
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: tempo-ingress
  namespace: monitoring
spec:
  podSelector:
    matchLabels:
      app.kubernetes.io/name: tempo
  policyTypes:
    - Ingress
  ingress:
    - from:
        - podSelector:
            matchLabels:
              app.kubernetes.io/name: grafana
      ports:
        - protocol: TCP
          port: 3200
    - from:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: default
      ports:
        - protocol: TCP
          port: 4317
        - protocol: TCP
          port: 4318

