apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: apps-db-migration
  namespace: flux-system
spec:
  dependsOn:
    - name: platform-cnpg-config
  interval: 10m
  retryInterval: 2m
  timeout: 5m
  prune: true
  wait: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./kubernetes/apps/base/db-migration
  postBuild:
    substituteFrom:
      - kind: ConfigMap
        name: cluster-vars
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: apps
  namespace: flux-system
spec:
  dependsOn:
    - name: apps-db-migration
    - name: platform-harbor
    - name: platform-cnpg-config
    - name: platform-agones
    - name: platform-nats
    - name: platform-image-automation
  interval: 10m
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./kubernetes/apps/overlays/replace-me
  prune: true
  wait: true
  timeout: 5m
  postBuild:
    substituteFrom:
      - kind: ConfigMap
        name: cluster-vars
