{
 "title": "Gameserver",
 "time": { "from": "now-30m", "to": "now" },
 "panels": [
  {
   "title": "Server Tick Rate Hz",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    { "expr": "game_server_tick_rate_hz", "legendFormat": "Tickrate (Hz)" }
   ]
  },
  {
   "title": "Connected Players",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    { "expr": "game_connected_players_count", "legendFormat": "Connected players" }
   ]
  },
  {
   "title": "Logs",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "{app=\"mmo-server\"} |= ``"
    }
   ]
  }
 ]
}