apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../base
  - ./provisioner.yml
patches:
  - path: patches/game-server-config-patch.yml
    target:
      kind: ConfigMap
      name: game-server-config
images:
  - name: rejdeboer/game-server
    newName: rejdeboer/game-server # {"$imagepolicy": "flux-system:game-server:name"}
    newTag: main-be91f23-1775998729 # {"$imagepolicy": "flux-system:game-server:tag"}
  - name: rejdeboer/web-server
    newName: rejdeboer/web-server # {"$imagepolicy": "flux-system:web-server:name"}
    newTag: main-be91f23-1775999394 # {"$imagepolicy": "flux-system:web-server:tag"}
