apiVersion: v1
kind: ConfigMap
metadata:
  name: mimir-alerts
  namespace: monitoring
data:
  alerts.yaml: |
    groups:
      - name: infrastructure
        rules:
          - alert: InstanceDown
            expr: up == 0
            for: 5m
            labels:
              severity: critical
            annotations:
              summary: "Instance {{ $labels.instance }} down"
              description: "{{ $labels.instance }} of job {{ $labels.job }} has been down for more than 5 minutes."
