apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: alertmanager-secret
  namespace: monitoring
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault-backend

  target:
    name: alertmanager-secret
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        alertmanager_fallback_config.yaml: |
          route:
            group_by: ['alertname', 'cluster', 'service']
            group_wait: 30s
            group_interval: 5m
            repeat_interval: 12h
            receiver: 'discord'
          receivers:
          - name: 'discord'
            slack_configs:
            - api_url: '{{ .discord_api_url }}'
              username: 'Mimir Alertmanager'
              send_resolved: true

  data:
  - secretKey: discord_api_url
    remoteRef:
      key: infrastructure/alertmanager
      property: discord_api_url

