apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: k8s-monitoring
  namespace: monitoring
spec:
  interval: 30m
  chart:
    spec:
      chart: k8s-monitoring
      version: "4.0.0"
      sourceRef:
        kind: HelmRepository
        name: grafana-charts
  valuesFrom:
  - kind: ConfigMap
    name: flux-kube-state-metrics-config
    valuesKey: kube-state-metrics-config.yml
  values:
    cluster:
      name: mmo

    destinations:
      hostedMetrics:
        type: prometheus
        url: "http://mimir-gateway.monitoring/api/v1/push"
      hostedLogs:
        type: loki
        url: "http://loki-gateway.monitoring/loki/api/v1/push"
      otlpGateway:
        type: otlp
        url: "tempo.monitoring.svc.cluster.local:4317"
        metrics: { enabled: true }
        logs:    { enabled: true }
        traces:  { enabled: true }

    clusterMetrics:
      enabled: true
      collector: alloy-metrics

    hostMetrics:
      enabled: true
      collector: alloy-metrics
      prometheus-node-exporter:
        enabled: true
      linuxHosts:
        enabled: true

    podLogsViaLoki:
      enabled: true
      collector: alloy-logs

    prometheusOperatorObjects:
      enabled: true
      collector: alloy-metrics

    telemetryServices:
      kube-state-metrics:
        deploy: true
      node-exporter:
        deploy: true

    collectors:
      alloy-metrics:
        presets: [clustered, statefulset]
        extraConfig: |-
          mimir.rules.kubernetes "mimir_rules" {
              address = "http://mimir-gateway.monitoring/prometheus/config/rules"
              tenant_id = "anonymous" 
          }
      alloy-logs:
        presets: [filesystem-log-reader, daemonset]

