apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: mimir
  namespace: monitoring
spec:
  interval: 30m
  chart:
    spec:
      version: "6.0.6"
      chart: mimir-distributed
      sourceRef:
        kind: HelmRepository
        name: grafana-charts
      interval: 60m
  values:
    global:
      extraEnvFrom:
      - secretRef:
          name: mimir-s3

    minio:
      enabled: false

    mimir:
      structuredConfig:
        common:
          storage:
            backend: s3
            s3:
              endpoint: ${AWS_ENDPOINT}
              insecure: true

        blocks_storage:
          s3:
            bucket_name: mimir-blocks
        ruler_storage:
          s3:
            bucket_name: mimir-ruler
        alertmanager_storage:
          s3:
            bucket_name: mimir-ruler

        # NOTE: Use classic deployment
        ingest_storage:
          enabled: false
        ingester:
          push_grpc_method_enabled: true
          ring:
            replication_factor: 1
            unregister_on_shutdown: true

    kafka:
      enabled: false
    alertmanager:
      enabled: true
      fallbackConfig: |
        route:
          group_by: ['alertname', 'cluster', 'service']
          group_wait: 30s
          group_interval: 5m
          repeat_interval: 12h
          receiver: 'discord'
        receivers:
        - name: 'discord'
          slack_configs:
          - api_url_file: /etc/secrets/alertmanager/discord-api-rul
            username: 'Mimir Alertmanager'
            send_resolved: true
      extraVolumes:
      - name: alertmanager-secret-vol
        secret:
          secretName: alertmanager-secret
      extraVolumeMounts:
      - name: alertmanager-secret-vol
        mountPath: /etc/secrets/alertmanager
        readOnly: true
    ruler:
      enabled: true
      extraVolumes:
      - name: rules-volume
        configMap:
          name: mimir-alerts
      extraVolumeMounts:
      - name: rules-volume
        mountPath: /data/ruler/anonymous/alerts.yaml
        subPath: alerts.yaml
        readOnly: true
    chunks-cache:
      enabled: false
    index-cache:
      enabled: false
    metadata-cache:
      enabled: false
    results-cache:
      enabled: false

    ingester:
      replicas: 2
      zoneAwareReplication:
        enabled: false
    distributor:
      replicas: 1
    querier:
      replicas: 1
    query_frontend:
      replicas: 1
    store_gateway:
      replicas: 1
      zoneAwareReplication:
        enabled: false
    compactor:
      replicas: 1
    rollout_operator:
      enabled: false
