apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: test
  namespace: monitoring
  labels:
    mimir_rule: "true"
spec:
  groups:
  - name: test
    rules:
      - alert: TestAlertPipeline
        expr: vector(1)
        labels:
          severity: critical
        annotations:
          summary: "This is a test alert"
          description: "If you are seeing this, Alloy synced the rule to Mimir, Mimir evaluated it, and sent it to Alertmanager!"
