apiVersion: mmo.rejdeboer.com/v1alpha1
kind: Realm
metadata:
  labels:
    app.kubernetes.io/name: realm
    app.kubernetes.io/managed-by: kustomize
  name: stormrage
spec:
  zoneSetRef: azeroth
  template:
    metadata:
      labels:
        app: zone-server
    spec:
      containers:
        - name: zone-server
          image: ghcr.io/rejdeboer/zone-server:latest
