{
 "title": "Gameserver",
 "time": { "from": "now-5m", "to": "now" },
 "panels": [
  {
   "title": "Server Tick Rate Hz",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    { "expr": "game_server_tick_rate_hz", "legendFormat": "Tickrate (Hz)" }
   ]
  },
  {
   "title": "Connected Players",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    { "expr": "game_connected_players_count", "legendFormat": "Connected players" }
   ]
  },
  {
   "title": "Incoming \\ outgoing bytes",
   "type": "timeseries",
   "gridPos": { "h": 16, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "rate(game_network_packets_total{direction=\"incoming\"}[$__rate_interval])",
     "legendFormat": "{{direction}} {{channel}}"
    },
    {
     "expr": "rate(game_network_packets_total{direction=\"outgoing\"}[$__rate_interval]) * -1",
     "legendFormat": "{{direction}} {{channel}}"
    }
   ]
  },
  {
   "title": "Server RTT P95",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum by(le) (rate(game_server_rtt_bucket[$__rate_interval])))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CPU usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum by (pod) (rate(container_cpu_usage_seconds_total{image!=\"\", container=\"game-server\"}[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Memory usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum by (pod) (container_memory_working_set_bytes{container=\"game-server\"})",
     "legendFormat": "Working set"
    },
    {
     "expr": "sum by (pod) (container_memory_rss{container=\"game-server\"})",
     "legendFormat": "RSS"
    }
   ]
  },
  {
   "title": "Gameserver logs",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "targets": [
    {
     "expr": "{app=\"game-server\"} |= ``"
    }
   ]
  },
  {
   "title": "Outgoing packets",
   "type": "stat",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 24 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(game_network_packets_total{direction=\"outgoing\"}[$__range]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Incoming packets",
   "type": "stat",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 24 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(game_network_packets_total{direction=\"incoming\"}[$__range]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Provisioner logs",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 32 },
   "targets": [
    {
     "expr": "{app=\"game-provisioner\"} |= ``"
    }
   ]
  },
  {
   "title": "Average outgoing packet size",
   "type": "stat",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(game_network_bytes_total{direction=\"outgoing\"}[$__range])) / sum(increase(game_network_packets_total{direction=\"outgoing\"}[$__range]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Average incoming packet size",
   "type": "stat",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(game_network_bytes_total{direction=\"incoming\"}[$__range])) / sum(increase(game_network_packets_total{direction=\"incoming\"}[$__range]))",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}