name: Destroy resources

on: 
  workflow_dispatch:

jobs:
  deploy:
    name: Destroy
    runs-on: ubuntu-latest
    environment: Production
    steps:
      - name: Checkout master
        uses: actions/checkout@master
        with:
          token: ${{ secrets.GH_PAT }}

      - name: Azure login
        uses: azure/login@v1
        with:
          client-id: ${{ vars.AZ_CLIENT_ID }} 
          tenant-id: ${{ vars.AZ_TENANT_ID }}
          subscription-id: ${{ vars.AZ_SUBSCRIPTION_ID }}
          enable-AzPSSession: false 

      - name: Destroy Infrastructure
        uses: ./.github/actions/destroy-terraform
        with:
          WORKING_DIRECTORY: ./terraform/production

