name: Destroy resources

on: 
  workflow_dispatch:

env:
  ARM_CLIENT_ID: ${{ vars.AZURE_CLIENT_ID }}
  ARM_SUBSCRIPTION_ID: ${{ vars.AZURE_SUBSCRIPTION_ID }}
  ARM_TENANT_ID: ${{ vars.AZURE_TENANT_ID }}
  
jobs:
  deploy:
    name: Destroy
    runs-on: ubuntu-latest
    environment: Production
    steps:
      - name: Checkout master
        uses: actions/checkout@master
        with:
          token: ${{ secrets.GH_PAT }}

      - name: Azure login
        uses: azure/login@v1
        with:
          client-id: ${{ vars.AZ_CLIENT_ID }} 
          tenant-id: ${{ vars.AZ_TENANT_ID }}
          subscription-id: ${{ vars.AZ_SUBSCRIPTION_ID }}
          enable-AzPSSession: false 

      - name: Destroy Infrastructure
        uses: ./.github/actions/destroy-terraform
        with:
          WORKING_DIRECTORY: ./terraform/production
        env:
          TF_VAR_cloudflare_api_token: ${{ secrets.CLOUDFLARE_API_TOKEN }}

